// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2MdGMUlbqZBBodhxqYYjwwcHeFfwG_Y',
    appId: '1:834461892197:android:b940851be9aef0411d108c',
    messagingSenderId: '834461892197',
    projectId: 'personalized-financial-a-48ac7',
    storageBucket: 'personalized-financial-a-48ac7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-vQ8-4-nGr2PzIyXCKudyDv8ebSe07EM',
    appId: '1:834461892197:ios:06e82132f1757c141d108c',
    messagingSenderId: '834461892197',
    projectId: 'personalized-financial-a-48ac7',
    storageBucket: 'personalized-financial-a-48ac7.firebasestorage.app',
    iosBundleId: 'com.example.personalizedFinancialAdvisor',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALE8kfRhaggRv-bjzSBZewypKh5OQXA-s',
    appId: '1:834461892197:web:972a4563ad0de8e11d108c',
    messagingSenderId: '834461892197',
    projectId: 'personalized-financial-a-48ac7',
    authDomain: 'personalized-financial-a-48ac7.firebaseapp.com',
    storageBucket: 'personalized-financial-a-48ac7.firebasestorage.app',
    measurementId: 'G-MF7F7PGJ5T',
  );

}